### PR TITLE
Implement buffer copies and transitions

### PR DESCRIPTION
**Pull request by Kangz**
PTAL

### CODE REVIEW

**Comment by Kangz** [comment]
Thanks for the review. I will rebase this on top of the Vulkan CI once it is landed.

**Comment by Kangz** [comment]
PTAL again, I added a commit at the beginning of the stack that should fix the compile error on 32bit.

**Comment by kainino0x** [comment]
Needs reformat though

**Comment by Kangz** [comment]
Merging manually, clang-format is having a formatting loop.

**Pull request merged**
